## PyTorch Vs Numpy

Check out this artcile on my blog [100 Days of Deep Learning](https://nandeshwar.in/100-days-of-deep-learning/matrix-maths-and-pytorch-tensor/).

PyTorch provides its own way of storing arrays just like NumPy which are known as Tensors. So technically array management provided by both the libraries are similar.

PyTorch Tensors are similar to NumPy library. One major difference is torch Tensors can run on GPUs. Tensors are also optimized for automatic differentiation. This are few of the many reasons why we prefer PyTorch Tensors over NumPy ndarrays.

In [1]:
import numpy as np
import torch

In [2]:
torch.__version__

'1.7.1'

### Initializing a tensor

In [3]:
# From Python lists
data = [[1, 2], [3, 4]]
x = torch.tensor(data)
x

tensor([[1, 2],
        [3, 4]])

In [4]:
# From NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

We can also create tensors based on other existing tensors. The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [5]:
x_ones = torch.ones_like(x)  # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [6]:
x_rand = torch.rand_like(x, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.9723, 0.4921],
        [0.3434, 0.8518]]) 



Now let us say we explicitly want to create a Tensor of shape (2, 3)

In [7]:
shape = (2, 3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3600, 0.5390, 0.1757],
        [0.9045, 0.8879, 0.9077]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
torch.randn((2,3,4))

tensor([[[-0.8103,  0.0284,  1.3068,  0.0236],
         [-0.3150, -0.7075,  0.6595, -0.2053],
         [ 0.2709,  1.4679,  1.4905, -0.4151]],

        [[-0.6823,  0.7472, -0.7822, -1.3015],
         [ 0.3270,  0.0740, -0.2777,  1.3253],
         [-0.1600, -2.6320, -0.8062, -1.1481]]])

> Each of its elements is randomly sampled from a standard Gaussian (normal) distribution with a mean of 0 and a standard deviation of 1.

In [10]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Attributes of a Tensor
Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [12]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [13]:
tensor.numel()

12

### Changing shapes

.shape is an alias for .size(), and was added to more closely match numpy, see [#1983](https://github.com/pytorch/pytorch/pull/1983)

In [14]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [15]:
print(f"Shape {X.shape}")
print(f"No. of elements {X.numel()}")
print(f"Size {X.size()}")

Shape torch.Size([3, 4])
No. of elements 12
Size torch.Size([3, 4])


In [16]:
x.reshape(3,-1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Sometimes we need to change the dimensions of data without actually changing its contents. This is done to make calculations more simple.

For example, there is a vector, which is one-dimensional but needs a matrix, which is two-dimensional. Notice that the content of all three tensors is the same.


In [17]:
v = torch.arange(5)
print(v, v.shape)

v1 = v.reshape((1,5))
print(v1, v1.shape)

v2 = v.reshape((5,1))
print(v1, v2.shape)

tensor([0, 1, 2, 3, 4]) torch.Size([5])
tensor([[0, 1, 2, 3, 4]]) torch.Size([1, 5])
tensor([[0, 1, 2, 3, 4]]) torch.Size([5, 1])


In [18]:
v = torch.arange(5)
print(v, v.shape)

v1 = v[None, :]
print(v1, v1.shape)

v2 = v[:, None]
print(v2, v2.shape)

tensor([0, 1, 2, 3, 4]) torch.Size([5])
tensor([[0, 1, 2, 3, 4]]) torch.Size([1, 5])
tensor([[0],
        [1],
        [2],
        [3],
        [4]]) torch.Size([5, 1])


## Operations on Tensors
Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling, and more. Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

> By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using the .to method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [19]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    print('GPU found')
    tensor = tensor.to('cuda')
else:
    print('No GPU')

No GPU


/home/iso-9/.local/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0


## Tensor Arithmetic Operations
All mathematical operations can be easily done on tensors.

In [20]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y  # The ** operator is exponentiation

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [21]:
# Get sum of a complete tensor
x.sum()

tensor(15.)

### Arithmetic operations with different shapes

In [22]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [23]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [24]:
a<b

tensor([[False,  True],
        [False, False],
        [False, False]])

### Tensors can be concatenated with each other in either dimensions

In [25]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.ones(12).reshape((3,4))
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  1.,  1.,  1.],
         [ 4.,  5.,  6.,  7.,  1.,  1.,  1.,  1.],
         [ 8.,  9., 10., 11.,  1.,  1.,  1.,  1.]]))

In [26]:
x.sum(), y.sum()

(tensor(66.), tensor(12.))

In [27]:
x==y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [28]:
x[:,1:] = 5

In [29]:
x = torch.arange(24 ).reshape(1,2,3,4)

In [30]:
x

tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],

         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]])

In [31]:
X = torch.arange(20, dtype=torch.float32).reshape(5,4)

In [32]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

Scalar, Vector, Matrix & Tensor representation

> Specifying axis=1 will reduce the column dimension (axis 1) by summing up elements of all the columns. Thus, the dimension of axis 1 of > Specifying axis=1 will reduce the column dimension (axis 1) by summing up elements of all the columns. Thus, the dimension of axis 1 of the input is lost in the output shape.the input is lost in the output shape.

In [33]:
torch.arange(20, dtype=torch.float32).reshape(5,4).sum(axis=1).shape

torch.Size([5])

In [34]:
X.mean(), X.sum()/X.numel()

(tensor(9.5000), tensor(9.5000))

In [35]:
X.mean(axis=0), X.sum(axis=0)/X.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [36]:
X.sum(axis=1), X.sum(axis=1).shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [37]:
X.sum(axis=1, keepdims=True), X.sum(axis=1, keepdims=True).shape

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 1]))

In [38]:
X.cumsum(axis=1)

tensor([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]])

In [39]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)

In [40]:
torch.dot(x,y)

tensor(6.)

In [41]:
(x*y).sum()

tensor(6.)

In [42]:
torch.mv(X,x)

tensor([ 14.,  38.,  62.,  86., 110.])

In [43]:
X, x

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]))

In [44]:
a = torch.arange(20).reshape(5,4)
b = torch.arange(12).reshape(4,3)

a, b

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]))

In [45]:
torch.mm(a,b)

tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262],
        [258, 312, 366],
        [330, 400, 470]])

In [46]:
torch.norm(torch.arange(10, dtype=torch.float32))

tensor(16.8819)

In [47]:
torch.arange(10, dtype=torch.float32).mean()

tensor(4.5000)

In [48]:
torch.arange(10, dtype=torch.float32)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [49]:
from math import sqrt
sqrt(sum([x**2 for x in range(10)]))

16.881943016134134

In [50]:
torch.abs(torch.arange(10)).sum()

tensor(45)

In [51]:
torch.arange(10).abs().sum()

tensor(45)

In [52]:
torch.arange(10, dtype=torch.float32).reshape(2,5).norm()

tensor(16.8819)

In [53]:
torch.ones((4,9)).norm()

tensor(6.)

In [54]:
# Prove that the transpose of a matrix  A ’s transpose is  A :  (A⊤)⊤=A .
torch.arange(10).reshape(2,5).T.T == torch.arange(10).reshape(2,5)

tensor([[True, True, True, True, True],
        [True, True, True, True, True]])

In [55]:
# Given two matrices  A  and  B , show that the sum of transposes is equal to the transpose of a sum:  A⊤+B⊤=(A+B)⊤ .
A = torch.arange(20).reshape(5, 4)
B = torch.ones(5,4)

A.T + B.T == (A+B).T

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [56]:
# Given any square matrix  A , is  A+A⊤  always symmetric? Why?
A = torch.arange(9).reshape(3,3)

A, A.T

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[0, 3, 6],
         [1, 4, 7],
         [2, 5, 8]]))

In [57]:
# We defined the tensor X of shape (2, 3, 4) in this section. What is the output of len(X)?

A = torch.arange(24).reshape(2, 3, 4)
A, len(A), A.shape, A.numel()

# 2 beacuse length of first dimension

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 2,
 torch.Size([2, 3, 4]),
 24)

In [58]:
# For a tensor X of arbitrary shape, does len(X) always correspond to the length of a certain axis of X? What is that axis?

# Yes, As above question len(X) always picks up first dimension

In [59]:
# Run A / A.sum(axis=1) and see what happens. Can you analyze the reason?

A = torch.arange(20).reshape(5, 4)

A + A.sum(axis=1, keepdims=True)

tensor([[ 6,  7,  8,  9],
        [26, 27, 28, 29],
        [46, 47, 48, 49],
        [66, 67, 68, 69],
        [86, 87, 88, 89]])

In [60]:
torch.arange(20).reshape(5, 4).sum(axis=0)

tensor([40, 45, 50, 55])

In [61]:
torch.arange(20).reshape(5, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

## References

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

https://rickwierenga.com/blog/machine%20learning/numpy-vs-pytorch-linalg.html

http://d2l.ai/chapter_preliminaries/#